# Generated by Django 4.0.3 on 2022-03-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_birth_date_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dp',
            field=models.FileField(blank=True, null=True, upload_to='uploads/profile/'),
        ),
    ]
