# Generated by Django 4.0.3 on 2022-03-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_werifierapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werifierapi',
            name='key',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='werifierapi',
            name='webhook',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
