# Generated by Django 4.0.3 on 2022-03-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_werifierapi_key_alter_werifierapi_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werifierapi',
            name='key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
