# Generated by Django 4.0.3 on 2022-03-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa', '0002_lead_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
