# Generated by Django 4.0.3 on 2022-03-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wa', '0003_lead_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='secret',
            new_name='sid',
        ),
    ]
