# Generated by Django 4.0.4 on 2022-04-30 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e', '0002_eapi_result_requestid'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestid',
            name='elist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e.elist'),
        ),
    ]
